---
- name: Copy ColdFusion installer
  copy:
      src: ../files/ColdFusion_2018_WWEJ_linux64.bin
      dest: /tmp/

- name: Copy ColdFusion silent.properties
  copy:
      src: ../files/silent.properties
      dest: /tmp/

- name: Install Coldfusion
  become: true
  become_method: sudo
  shell: bash /tmp/ColdFusion_2018_WWEJ_linux64.bin -f silent.properties

- name: start Coldfusion admin
  become: true
  become_method: sudo
  shell: bash /opt/coldfusion2018/cfusion/bin/coldfusion start
